Class {
	#name : #JiraPharoComponent,
	#superclass : #Object,
	#instVars : [
		'id',
		'name'
	],
	#category : #'JiraPharoAPI-Model'
}

{ #category : #accessing }
JiraPharoComponent >> id [

	^ id
]

{ #category : #accessing }
JiraPharoComponent >> id: anObject [

	id := anObject
]

{ #category : #accessing }
JiraPharoComponent >> name [

	^ name
]

{ #category : #accessing }
JiraPharoComponent >> name: anObject [

	name := anObject
]
